CREATE DATABASE asimpletrade CHARACTER SET utf8  ;
USE asimpletrade;

CREATE TABLE USER (
id int(5) NOT NULL auto_increment,
name VARCHAR(40) NOT NULL,
firstname VARCHAR(40) NOT NULL,
login VARCHAR(40) NOT NULL UNIQUE,
password VARCHAR(180) NOT NULL,
mail VARCHAR(80) NOT NULL,
address VARCHAR(120) NOT NULL,
phone VARCHAR(30) NOT NULL,
portable VARCHAR(30) NOT NULL,
subscription_date DATETIME NOT NULL,
hash VARCHAR(180),
newsletter BOOLEAN NOT NULL DEFAULT 0,
role ENUM('administrator', 'user') NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE ANNOUNCEMENT (
id INT(5) NOT NULL auto_increment, 
title VARCHAR(80) NOT NULL,
subtitle VARCHAR(80),
content TEXT NOT NULL,
post_date DATETIME NOT NULL,
conclued BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE PICTURE (
id INT(5) NOT NULL auto_increment,
title VARCHAR(80),
alternative VARCHAR(80),
path VARCHAR(180) NOT NULL,
height VARCHAR(4),
width VARCHAR(4),
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE INCOMING (
id INT(5) NOT NULL auto_increment,
title VARCHAR(80) NOT NULL,
subtitle VARCHAR(80),
content TEXT NOT NULL,
post_date DATETIME NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE MESSAGE (
id INT(5) NOT NULL auto_increment,
subject VARCHAR(80) NOT NULL,
content TEXT NOT NULL,
date_post DATETIME NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE TO_APPLY (
id_user INT(5) NOT NULL,
id_announcement INT(5) NOT NULL,
FOREIGN KEY(id_user) REFERENCES USER(id),
FOREIGN KEY(id_announcement) REFERENCES ANNOUNCEMENT(id)) ENGINE=InnoDB;

CREATE TABLE TO_ASSOCIATE (
id_announcement INT(5) NOT NULL,
id_tag INT(5) NOT NULL,
FOREIGN KEY(id_announcement) REFERENCES ANNOUNCEMENT,
FOREIGN KEY(id_tag) REFERENCES TAG(id)) ENGINE=InnoDB;

CREATE TABLE TO_FOLLOW ( 
id_user_followed INT(5) NOT NULL,
id_user_follower INT(5) NOT NULL,
FOREIGN KEY(id_user_followed) REFERENCES USER(id),
FOREIGN KEY(id_user_follower) REFERENCES USER(id)) ENGINE=InnoDB;

CREATE TABLE TO_EVALUATE (
id_user INT(5) NOT NULL,
id_announcement INT(5) NOT NULL,
mark INT(2) NOT NULL,
FOREIGN KEY(id_user) REFERENCES USER(id),
FOREIGN KEY(id_announcement) REFERENCES ANNOUNCEMENT(id)) ENGINE=InnoDB;

