CREATE DATABASE asimpletrade;
USE asimpletrade;

CREATE TABLE USER (
id int(5) NOT NULL auto_increment,
name VARCHAR(40) NOT NULL,
firstname VARCHAR(40) NOT NULL,
login VARCHAR(40) NOT NULL,
password VARCHAR(180) NOT NULL,
mail VARCHAR(80) NOT NULL,
address VARCHAR(120) NOT NULL,
phone VARCHAR(30) NOT NULL,
portable VARCHAR(30) NOT NULL,
subscription_date DATETIME NOT NULL,
hash VARCHAR(180),
newsletter BOOLEAN NOT NULL DEFAULT 0,
admin BOOLEAN NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE ANNOUNCEMENT (
id INT(5) NOT NULL auto_increment, 
title VARCHAR(80) NOT NULL,
subtitle VARCHAR(80),
content TEXT NOT NULL,
post_date DATETIME NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE ANNOUNCEMENT_TYPE (
id INT(5) NOT NULL auto_increment,
label VARCHAR(30),
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE PICTURE (
id INT(5) NOT NULL auto_increment,
title VARCHAR(80),
alternative VARCHAR(80),
path VARCHAR(180) NOT NULL,
height VARCHAR(4),
width VARCHAR(4),
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE NEWS (
id INT(5) NOT NULL auto_increment,
title VARCHAR(80) NOT NULL,
subtitle VARCHAR(80),
content TEXT NOT NULL,
post_date DATETIME NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

CREATE TABLE MESSAGE (
id INT(5) NOT NULL auto_increment,
subject VARCHAR(80) NOT NULL,
content TEXT NOT NULL,
date_post DATETIME NOT NULL,
PRIMARY KEY(id)) ENGINE=InnoDB;

